# Generated by Django 2.2.5 on 2020-05-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200517_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=8),
        ),
    ]
